# These are supported funding model platforms

github: 4211421036
patreon: GalihRidhoUtomo
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: #facemind
community_bridge: #facemind
liberapay: galihridhoutomo
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: 
- 'https://www.paypal.me/GALIHRIDHOUTOMO'
